spring:
#  application:
#    name: merchant-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sc_demo?serverTimezone=Asia/Shanghai&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123
#  cloud:
#    nacos:
#      server-addr: localhost:8848  #nacos服务端地址
#      discovery:
#        namespace: 1977953c-6185-4552-92d0-71e07bf05301  #命名空间设置
#        cluster-name: ZS  #集群名称


#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:7000/eureka

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-not-delete-value: 0
      logic-delete-field: deleted
      logic-delete-value: 1
      id-type: assign_uuid

server:
  port: 8092