spring:
  application:
    name: commodityservice
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sc_demo?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
    nacos:
      server-addr: 47.120.15.196:8848  #nacos服务端地址
      discovery:
        cluster-name: ZZ  #集群名称
#        namespace: 1977953c-6185-4552-92d0-71e07bf05301  #命名空间设置
#        ephemeral: false  #是否是临时实例
    sentinel:
      transport:
        dashboard: localhost:8080


#merchant-service:
#  ribbon:
#    NFLoadBalancerRuleClassName: com.alibaba.cloud.nacos.ribbon.NacosRule

#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:7000/eureka

#merchant-service:
#  ribbon:
#    NF

#ribbon:
#  eager-load:
#    enabled: true
#    clients:
#      - merchant-service
#      - xxx-server
feign:
  httpclient:
    enabled: true  #支持httpclient的开关
    max-connections: 200  #最大连接数
    max-connections-per-route: 50 #单个路径的最大连接数
  sentinel:
    enabled: true  #开启feign对sentinel的支持
#  client:
#    config:
#      default:
#        loggerLevel: FULL
#        #BASIC


mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-not-delete-value: 0
      logic-delete-field: deleted
      logic-delete-value: 1
      id-type: assign_uuid
  mapper-locations: classpath*:mapper/**/*Mapper.xml

logging:
  pattern:
    dateformat: yyyy-MM-dd HH:mm:ss:SSS

server:
  port: 8091
