spring:
  application:
    name: feign-api

feign:
  httpclient:
    enabled: true  #支持httpclient的开关
    max-connections: 200  #最大连接数
    max-connections-per-route: 50 #单个路径的最大连接数
  client:
    config:
      default:
        loggerLevel: basic #full、null

server:
  port: 8089